export const pricing = [
  {
    id: "launch",
    name: "Launch",
    price: "From £600",
    description: "Perfect for startups and local businesses.",
    featuresLabel: "Includes",
    features: [
      "Up to 5 pages",
      "Custom design",
      "Mobile responsive",
      "Contact form",
      "Basic SEO",
      "Google Analytics",
      "Google Search Console",
      "Google Business Profile setup",
      "Website speed optimisation",
      "1 month support",
    ],
    delivery: "1–2 weeks",
    highlighted: false,
    cta: { label: "Enquire", href: "#contact" },
  },
  {
    id: "growth",
    name: "Growth",
    price: "From £1,000",
    description: "Ideal for established businesses.",
    featuresLabel: "Everything in Launch plus",
    features: [
      "Up to 10 pages",
      "Blog/CMS",
      "Advanced animations",
      "Improved SEO",
      "Copywriting assistance",
      "Google Ads setup",
      "Conversion optimisation",
      "Booking forms",
      "Training session",
    ],
    delivery: "2–4 weeks",
    highlighted: true,
    cta: { label: "Enquire", href: "#contact" },
  },
  {
    id: "scale",
    name: "Scale",
    price: "From £1,700",
    description: "For businesses ready to invest in growth.",
    featuresLabel: "Everything in Growth plus",
    features: [
      "Brand strategy",
      "Full visual identity",
      "Custom illustrations",
      "Logo design",
      "E-commerce",
      "Advanced integrations",
      "CRM integration",
      "Email marketing setup",
      "Ongoing optimisation",
      "Performance reports",
    ],
    delivery: "4–8 weeks",
    highlighted: false,
    cta: { label: "Enquire", href: "#contact" },
  },
];

export const pricingAddOns = [
  { service: "Visual Identity", price: "£500" },
  { service: "Brand Strategy", price: "£400" },
  { service: "Logo Design", price: "£250" },
  { service: "Additional Page", price: "£75" },
  { service: "E-Commerce Integration", price: "£800" },
  { service: "Booking System Integration", price: "£300" },
  { service: "SEO Audit & Optimisation", price: "£300" },
  { service: "Digital Marketing", price: "£500/mo" },
  { service: "Google Analytics & Search Console Setup", price: "£100" },
  { service: "Website Maintenance & Updates", price: "£75/mo" },
  { service: "Priority Support", price: "£150/mo" },
];
